version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketsapp
    image: ticketsapp:latest
    ports:
      - "8080:8080"
    networks:
      - my-net
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ticketsDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Root123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    networks:
      - my-net
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=imendoza@unab.edu.co
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge